spring:
  mvc:
    date-format: yyyy-MM-dd
  datasource:
    username: root
    password: 123123123
    url: jdbc:mysql://localhost:3306/cms?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  messages:
    basename: i18n/messages

  jpa:
    hibernate:
      ddl-auto: create # update: ?? Model ???????
    show-sql: true

  servlet:
    multipart:
      max-file-size: 3GB # ??????
      max-request-size: 3GB
#
#server:
#  port: 90
